bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
main.sh -c
bash -f main.sh -c
bash -f main.sh
bash -f main.sh -c
bash -f main.sh
bash -f main.sh -c
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
bash -f main.sh
